[package]
name = "occ"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
glam.workspace = true
hecs.workspace = true
log.workspace = true
raw-window-handle.workspace = true
sdl3 = { workspace = true }
occ-common.workspace = true
occ-components.workspace = true
occ-render-vk.workspace = true
occ-systems.workspace = true
